name: Coverage Badge

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/coverage.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/coverage.yml'

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    services:
      memcached:
        image: memcached:1.6-alpine
        ports:
          - 11211:11211

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        uv sync
        uv add genbadge[coverage]

    - name: Activate virtual environment and generate coverage report
      run: |
        source .venv/bin/activate
        coverage run -m pytest
        coverage report
        coverage xml
        genbadge coverage -i coverage.xml -o coverage.svg

    - name: Upload coverage badge
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: coverage-badge
        folder: .
        target-folder: .
        clean: false
